[tool.black]
include = '''
          (
            ^.*\.pyi?$
            | run/publish_behave_logs/publish_behave_logs$
          )
          '''

[[tool.mypy.overrides]]
module = [
    "behave",
    "dbus",
    "pexpect",
    "pyinotify",
    "pyroute2",
    "selinux",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
junit_logging = "all"
junit_log_passing_tests = false
