[tool.black]
include = '''
          (
            ^.*\.pyi?$
            | run/fedora-vagrant/nmtest$
            | run/publish_behave_logs/publish_behave_logs$
          )
          '''

[tool.mypy]
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "behave.*",
    "dbus",
    "features.steps.nmtui.*",
    "ipdb",
    "pexpect",
    "pyinotify",
    "pyroute2",
    "selinux",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
junit_logging = "all"
junit_log_passing_tests = false
