- name: "set up behave logs publishing"
  hosts: "*"
  remote_user: "root"
  vars:
    inst_pkgs:
      - "httpd"
    inst_pkgs_2:
      - "python3-libselinux"
      - "python3-inotify"
  tasks:
    - name: "install stuff"
      ansible.builtin.package:
        name: "{{ inst_pkgs + inst_pkgs_2 }}"
        state: "present"

    - name: "override welcome.conf"
      ansible.builtin.copy:
        dest: "/etc/httpd/conf.d/welcome.conf"
        content: |
            # disable welcome page
      notify: "restart httpd"

    - name: "create document root directory"
      ansible.builtin.file:
        path: "/var/www/html"
        state: "directory"

    - name: "set up root directory listing"
      ansible.builtin.copy:
        src: "99-publish_behave_logs.conf"
        dest: "/etc/httpd/conf.d/99-publish_behave_logs.conf"
      notify: "restart httpd"

    - name: "set Listen 8080"
      ansible.builtin.lineinfile:
        path: "/etc/httpd/conf/httpd.conf"
        regexp: "^Listen [0-9:]+"
        line: "Listen 8080"
      notify: "restart httpd"

    - name: "copy log helper"
      ansible.builtin.copy:
        src: "publish_behave_logs"
        dest: "/usr/local/bin/"
        mode: "0755"
      notify: "restart p_b_l"

    - name: "copy log helper service"
      ansible.builtin.copy:
        src: "publish_behave_logs.service"
        dest: "/etc/systemd/system/"
      register: "service_copied"

    - name: "reload systemd"
      ansible.builtin.systemd:
        daemon_reload: true
      when: service_copied.changed
      notify: "restart p_b_l"

    - name: "enable and start httpd"
      ansible.builtin.systemd:
        name: "httpd.service"
        enabled: true
        state: "started"

    - name: "start publish_behave_logs"
      ansible.builtin.systemd:
        name: "publish_behave_logs.service"
        state: "started"
        enabled: true

  handlers:
    - name: "restart httpd"
      ansible.builtin.systemd:
        name: "httpd"
        state: "restarted"

    - name: "restart p_b_l"
      ansible.builtin.systemd:
        name: "publish_behave_logs"
        state: "restarted"
