#!/bin/bash
set -x

if [ -n "$1" ];then
        . ./setup.sh
        ip tuntap add $1 mode tap user `whoami`
        #vlan33@tap
        ip link add link $1 name $1.33 type vlan id 33

        # up the links
        ip link set dev $1 up
        ip link set dev $1.33 up
        ip addr add 192.168.55.21/30 dev $1
        ip addr add 192.168.55.33/29 dev $1.33
        stop_dhcp
        start_dhcp
        echo "ip link del $1" >> /tmp/dracut_vlan_tap
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi
